### ISSUE TITLE
plugin fails to load

### ISSUE THREAD

**Issue by Fealthas** [fdw/ranger-autojump#1]
Manjaro, i3 edition. Bash.

File was placed in specified directory.
When running ranger from terminal, a message about the auto-jump plugin failing to load appears. Does not work in the program.

**Comment by fdw** [comment]
So apparently ranger detects the file. What exactly is the error message? What are your ranger and autojump versions?

**Comment by Fealthas** [comment]
I tried deleting the old .py and replacing it with a new download of it. Seems to have fixed the problem. Thanks for the plugin btw!

Can close.

**Comment by fdw** [comment]
That's good 🙂 Have fun!
