### ISSUE TITLE
Async autojump add

### ISSUE THREAD

**Issue by danyfedorov** [fdw/ranger-autojump#2]
Hi, what do you think about using `subprocess.Popen` to make it non-blocking? `subprocess.call` makes my Pentium laptop freeze every time I cd :)

I mean
```python
subprocess.Popen(["autojump", "--add", signal.new.path])
```

**Comment by fdw** [comment]
That sounds like a good idea, thanks! :)

I'll see when I find the time to implement it.

**Comment by fdw** [comment]
Should be implemented now :)

**Comment by danyfedorov** [comment]
Thank you! 
I was worried that using Popen without afterwards killing the process could result in a bunch of zombie processes, but it actually results in only one. After I cd, I can see a zombie process of `autojump` in htop. After the next cd, the old process is killed and is replaced by the new one. A single zombie process is ok, I think.
