### ISSUE TITLE
Not working in Ubuntu

### ISSUE THREAD

**Issue by bill-mccormick-dg** [fdw/ranger-autojump#4]
Copied autojump.py to ~/.config/ranger/plugins.

At some point (after running ranger?) I see:
`
.rw-rw-r--    0 wmccormick wmccormick 20 Mar  8:28 __init__.py
.rw-rw-r--  138 wmccormick wmccormick 20 Mar  8:28 __init__.pyo
.rw-rw-r--  659 wmccormick wmccormick 20 Mar  8:09 autojump.py
.rw-rw-r-- 1.4k wmccormick wmccormick 20 Mar  8:28 autojump.pyo
`
But :j in ranger says "command not found". I assume that, although not detailed under _Installation_, it is also required that autojump itself be installed, which I did.

**Comment by fdw** [comment]
What is the output `which autojump`? Is autojump on the path?

**Comment by s0553407** [comment]
Can confirm `command not found: j`.
Using opensuse tumbleweed.
`which autojump` gives me `/usr/bin/autojump` (installed from opensuse repos).

**Comment by fdw** [comment]
Some more questions: Is it listed in the commands help in ranger (In ranger, press `h`, then `c`)?
What is the output if you start `ranger --debug` and try to call `:j`?

**Comment by fdw** [comment]
Since I have not heard back from you, @wpmccormick, I will close this ticket. Feel free to re-open if you have new information.
